#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew update
brew install wget 
brew install libxml2
brew install glib
brew install popt
brew install pkg-config
./install_linux
